### ISSUE TITLE
Search view hidden on android 7.1

### ISSUE THREAD

**Issue by scrummitch** [paramsen/autocomplete-toolbar-search-view#1]
Hey Par! Its mitch here

Just wanted to let you know theres a bit of an issue with the search view. It seems like that on android 7.1 the top of the search view is cut off. 

How to reproduce:
 1. download 7.1 simulator
 2. run the included demo
 3. type any character
 4. top search bar will disappear 

Heres a screen:
<img width="497" alt="screen shot 2017-08-16 at 2 32 57 pm" src="https://user-images.githubusercontent.com/990013/29347408-dda0dbdc-828f-11e7-8d0d-fb01283ff4fa.png">

**Comment by mak12** [comment]
@scrummitch having same issue, you got any luck with that??

**Comment by scrummitch** [comment]
@mak12 yes but i forgot how i fixed it, such a long time ago!

**Comment by HiteshDevganiya** [comment]
You have to change `findToolbar` method in `ViewUtils`. In my case, I have to add `androidx.appcompat.widget.Toolbar`

**Comment by paramsen** [comment]
Hey 👋 Hope this piece of code fullfilled its purpose 😊/ Pär Amsen9 jan. 2024 kl. 03:15 skrev Mitch ***@***.***>:﻿
Closed #1 as completed.
